"""empty message

Revision ID: 03896c1fdc9f
Revises: 32fa64216988
Create Date: 2019-12-17 19:53:09.718038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03896c1fdc9f'
down_revision = '32fa64216988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=80), nullable=False),
    sa.Column('lname', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('comuna', sa.String(length=80), nullable=True),
    sa.Column('address_1', sa.String(length=120), nullable=True),
    sa.Column('address_2', sa.String(length=120), nullable=True),
    sa.Column('rut', sa.String(length=10), nullable=True),
    sa.Column('rut_serial', sa.String(length=20), nullable=True),
    sa.Column('score_as_provider', sa.Float(), nullable=True),
    sa.Column('score_as_employer', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'comuna')
    op.drop_column('users', 'rut_serial')
    op.drop_column('users', 'address_1')
    op.drop_column('users', 'fname')
    op.drop_column('users', 'score_as_provider')
    op.drop_column('users', 'lname')
    op.drop_column('users', 'address_2')
    op.drop_column('users', 'region')
    op.drop_column('users', 'score_as_employer')
    op.drop_column('users', 'rut')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rut', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('score_as_employer', mysql.FLOAT(), nullable=True))
    op.add_column('users', sa.Column('region', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('users', sa.Column('address_2', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('users', sa.Column('lname', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('users', sa.Column('score_as_provider', mysql.FLOAT(), nullable=True))
    op.add_column('users', sa.Column('fname', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('users', sa.Column('address_1', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('users', sa.Column('rut_serial', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('users', sa.Column('comuna', mysql.VARCHAR(length=80), nullable=True))
    op.drop_table('userinfo')
    # ### end Alembic commands ###
