"""empty message

Revision ID: 32fa64216988
Revises: ee45bdb33df7
Create Date: 2019-12-17 19:42:56.140528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32fa64216988'
down_revision = 'ee45bdb33df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userRole', sa.String(length=10), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('serviceID', sa.Integer(), nullable=False),
    sa.Column('fromUserID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fname', sa.String(length=80), nullable=False),
    sa.Column('lname', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('comuna', sa.String(length=80), nullable=True),
    sa.Column('address_1', sa.String(length=120), nullable=True),
    sa.Column('address_2', sa.String(length=120), nullable=True),
    sa.Column('rut', sa.String(length=10), nullable=True),
    sa.Column('rut_serial', sa.String(length=20), nullable=True),
    sa.Column('score_as_provider', sa.Float(), nullable=True),
    sa.Column('score_as_employer', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_index('email', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('fname', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('lname', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user', ['username'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_table('users')
    op.drop_table('reviews')
    # ### end Alembic commands ###
