"""empty message

Revision ID: 49d4a4efaac6
Revises: a7c7e91b8748
Create Date: 2019-12-20 13:09:16.669804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d4a4efaac6'
down_revision = 'a7c7e91b8748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contract', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_column('contract', 'user_id')
    # ### end Alembic commands ###
