"""empty message

Revision ID: a7c7e91b8748
Revises: 4ebd99bea7b1
Create Date: 2019-12-19 16:22:43.981409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7c7e91b8748'
down_revision = '4ebd99bea7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_status', sa.String(length=10), nullable=False),
    sa.Column('contract_date', sa.DateTime(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cotract')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotract',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('contract_status', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('contract_date', mysql.DATETIME(), nullable=False),
    sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name='cotract_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('contract')
    # ### end Alembic commands ###
